package ca.ualberta.CMPUT301F13T02.chooseyouradventure.elasticsearch;

/*
 * Represents 'hits' statistics as generated by Elastic Search 
 */

/* The file modified from https://github.com/rayzhangcl/ESDemo */

import java.util.Collection;


public class ESHits<T> {
    int total;
    double max_score;
    Collection<ESResponse<T>> hits;

    public Collection<ESResponse<T>> getHits() {
        return hits;
    }

    public String toString() {
        return (super.toString() + "," + total + "," + max_score + "," + hits);
    }
}