package ca.ualberta.CMPUT301F13T02.chooseyouradventure.elasticsearch;

/*
 * Encapsulates query responses as generated by Elastic Search 
 */

/* The file modified from https://github.com/rayzhangcl/ESDemo */

public class ESResponse<T> {
    String _index;
    String _type;
    String _id;
    int _version;
    boolean exists;
    T _source;
    double max_score;

    public T getSource() {
        return _source;
    }
}
